### ISSUE TITLE
keycloak-k8s-resources nightly not updating the kubernetes resources

### ISSUE THREAD

**Issue by ahus1** [keycloak-rel/keycloak-rel#46]
The latest changes built a new operator image, but failed to update the nightly branch of the kubernetes-k8s-resources repositor: 
https://github.com/keycloak/keycloak-k8s-resources/tree/nightly/kubernetes

The resources there are two months old. As they don't contain the latest changes when the operator changed from "deployment" to "statefulset", the current nightly operator image can't be installed with the resources provided in that repository branch. 

Even though the latest action is now green, the changes didn't end up there: https://github.com/keycloak-rel/keycloak-rel/runs/7832196596?check_suite_focus=true

**Comment by ahus1** [comment]
I think I might have found the problem: 

* previously the nightly build updated a nightly branch 
  -> https://github.com/keycloak/keycloak-k8s-resources/tree/nightly/kubernetes
* now it creates / updates a nightly tag 
  -> https://github.com/keycloak/keycloak-k8s-resources/tree/refs/tags/nightly/kubernetes

@vmuzikar - should the nightly branch be deleted to avoid confusion? Or should the nightly build update the branch rather than creating a nightly tag from main?

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the report and for finding to root cause. I have removed the `nightly` branch as we're now using the tag instead, which makes it aligned with the rest of KC repos.

However, we should consider also updating the `main` branch as it is also confusing that it is never updated. Created https://github.com/keycloak-rel/keycloak-rel/issues/49 for it.
